### ISSUE TITLE
Changing background colour after each timer?

### ISSUE THREAD

**Issue by sje30** [maruta/timekeeper#1]
Hi, 
this is a great timer, thank you!

Is there a way to change the background colour after each chime?  e.g. for a 25 minute talk, if the first timer is set to 20 minutes, and the second to 25 minutes, then after 20 minutes the background could change to yellow, and then after 25 minutes to red?

Happy to hack a solution if you think this is doable!

**Comment by sje30** [comment]
It turned out to be simple to fix this, by adding a line  such as below after a chime is played.

```
 audio_chime1.play();
 document.body.style.backgroundColor = "ForestGreen";
```

I also needed to reset the colour to black just after this chunk:

```
$('.nav #standby').click(function (event){
    event.preventDefault();
    $('.nav li').removeClass('active');
    $('.nav li#standby').addClass('active');
```

I can hard-code colours in my own version, but would it be worth adding these as parameters that can be passed in the URL?

Would you like a PR with hard-coded colours?

**Comment by sje30** [comment]
ah, sorry, I just saw you have made some neater solution to this problem.  Thank you!  Should I try this version?

**Comment by maruta** [comment]
Thank you for your comments!
Since I think many people will want their own customization, 
I'm searching for some solution to make such customization easy.
And as you found, I implemented some idea and want to try this for a while.

Thanks again for productive comments!

**Comment by sje30** [comment]
Thank you for such great work.  I look forward to using your timer in
conferences.

Stephen
