### ISSUE TITLE
Adding Countdown-timer feature

### ISSUE THREAD

**Issue by rcarrata** [maruta/timekeeper#9]
Hello! 

Adding a Countdown-Timer feature as an option for the Timekeeper could be a nice feature to add.

Thanks for developing this nice timekeeper @maruta!

**Comment by maruta** [comment]
Thank you!
 I made it work as a simple countdown timer. c17991c6c04c44c0bba556a470b35a19c16200fe

[Example](http://maruta.github.io/timekeeper/#t0=-15:00&t1=-10:00&t2=-5:00&t3=0:00&m=Click%20to%20edit%20this%20message.)
